inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

require:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Exclude:
    - spec/system/*
