# fly.toml app configuration file generated for smartlottery on 2023-09-16T14:48:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartlottery"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[processes]
  web = "bin/rails server"
  cron = "supercronic /rails/crontab"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
